// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorResponseErrorCode.
const (
	NOCANDIDATE ErrorResponseErrorCode = "NO_CANDIDATE"
	NOTASSIGNED ErrorResponseErrorCode = "NOT_ASSIGNED"
	NOTFOUND    ErrorResponseErrorCode = "NOT_FOUND"
	PREXISTS    ErrorResponseErrorCode = "PR_EXISTS"
	PRMERGED    ErrorResponseErrorCode = "PR_MERGED"
	TEAMEXISTS  ErrorResponseErrorCode = "TEAM_EXISTS"
)

// Defines values for PullRequestStatus.
const (
	PullRequestStatusMERGED PullRequestStatus = "MERGED"
	PullRequestStatusOPEN   PullRequestStatus = "OPEN"
)

// Defines values for PullRequestShortStatus.
const (
	PullRequestShortStatusMERGED PullRequestShortStatus = "MERGED"
	PullRequestShortStatusOPEN   PullRequestShortStatus = "OPEN"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// PullRequest defines model for PullRequest.
type PullRequest struct {
	// AssignedReviewers user_id назначенных ревьюверов (0..2)
	AssignedReviewers []string          `json:"assigned_reviewers"`
	AuthorId          string            `json:"author_id"`
	CreatedAt         *time.Time        `json:"createdAt"`
	MergedAt          *time.Time        `json:"mergedAt"`
	PullRequestId     string            `json:"pull_request_id"`
	PullRequestName   string            `json:"pull_request_name"`
	Status            PullRequestStatus `json:"status"`
}

// PullRequestStatus defines model for PullRequest.Status.
type PullRequestStatus string

// PullRequestShort defines model for PullRequestShort.
type PullRequestShort struct {
	AuthorId        string                 `json:"author_id"`
	PullRequestId   string                 `json:"pull_request_id"`
	PullRequestName string                 `json:"pull_request_name"`
	Status          PullRequestShortStatus `json:"status"`
}

// PullRequestShortStatus defines model for PullRequestShort.Status.
type PullRequestShortStatus string

// Team defines model for Team.
type Team struct {
	Members  []TeamMember `json:"members"`
	TeamName string       `json:"team_name"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// User defines model for User.
type User struct {
	IsActive bool   `json:"is_active"`
	TeamName string `json:"team_name"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// TeamNameQuery defines model for TeamNameQuery.
type TeamNameQuery = string

// UserIdQuery defines model for UserIdQuery.
type UserIdQuery = string

// PostPullRequestCreateJSONBody defines parameters for PostPullRequestCreate.
type PostPullRequestCreateJSONBody struct {
	AuthorId        string `json:"author_id"`
	PullRequestId   string `json:"pull_request_id"`
	PullRequestName string `json:"pull_request_name"`
}

// PostPullRequestMergeJSONBody defines parameters for PostPullRequestMerge.
type PostPullRequestMergeJSONBody struct {
	PullRequestId string `json:"pull_request_id"`
}

// PostPullRequestReassignJSONBody defines parameters for PostPullRequestReassign.
type PostPullRequestReassignJSONBody struct {
	OldUserId     string `json:"old_user_id"`
	PullRequestId string `json:"pull_request_id"`
}

// PostTeamDeactivateJSONBody defines parameters for PostTeamDeactivate.
type PostTeamDeactivateJSONBody struct {
	// TeamName Имя команды для деактивации
	TeamName string `json:"team_name"`
}

// GetTeamGetParams defines parameters for GetTeamGet.
type GetTeamGetParams struct {
	// TeamName Уникальное имя команды
	TeamName TeamNameQuery `form:"team_name" json:"team_name"`
}

// GetUsersGetReviewParams defines parameters for GetUsersGetReview.
type GetUsersGetReviewParams struct {
	// UserId Идентификатор пользователя
	UserId UserIdQuery `form:"user_id" json:"user_id"`
}

// PostUsersSetIsActiveJSONBody defines parameters for PostUsersSetIsActive.
type PostUsersSetIsActiveJSONBody struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
}

// PostPullRequestCreateJSONRequestBody defines body for PostPullRequestCreate for application/json ContentType.
type PostPullRequestCreateJSONRequestBody PostPullRequestCreateJSONBody

// PostPullRequestMergeJSONRequestBody defines body for PostPullRequestMerge for application/json ContentType.
type PostPullRequestMergeJSONRequestBody PostPullRequestMergeJSONBody

// PostPullRequestReassignJSONRequestBody defines body for PostPullRequestReassign for application/json ContentType.
type PostPullRequestReassignJSONRequestBody PostPullRequestReassignJSONBody

// PostTeamAddJSONRequestBody defines body for PostTeamAdd for application/json ContentType.
type PostTeamAddJSONRequestBody = Team

// PostTeamDeactivateJSONRequestBody defines body for PostTeamDeactivate for application/json ContentType.
type PostTeamDeactivateJSONRequestBody PostTeamDeactivateJSONBody

// PostUsersSetIsActiveJSONRequestBody defines body for PostUsersSetIsActive for application/json ContentType.
type PostUsersSetIsActiveJSONRequestBody PostUsersSetIsActiveJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check endpoint
	// (GET /health)
	GetHealth(c *gin.Context)
	// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
	// (POST /pullRequest/create)
	PostPullRequestCreate(c *gin.Context)
	// Пометить PR как MERGED (идемпотентная операция)
	// (POST /pullRequest/merge)
	PostPullRequestMerge(c *gin.Context)
	// Переназначить конкретного ревьювера на другого из его команды
	// (POST /pullRequest/reassign)
	PostPullRequestReassign(c *gin.Context)
	// Получить статистику назначений по пользователям
	// (GET /statistics/assignments)
	GetStatisticsAssignments(c *gin.Context)
	// Получить рабочую нагрузку активных пользователей
	// (GET /statistics/workload)
	GetStatisticsWorkload(c *gin.Context)
	// Создать команду с участниками (создаёт/обновляет пользователей)
	// (POST /team/add)
	PostTeamAdd(c *gin.Context)
	// Массовая деактивация пользователей команды с переназначением PR
	// (POST /team/deactivate)
	PostTeamDeactivate(c *gin.Context)
	// Получить команду с участниками
	// (GET /team/get)
	GetTeamGet(c *gin.Context, params GetTeamGetParams)
	// Получить PR'ы, где пользователь назначен ревьювером
	// (GET /users/getReview)
	GetUsersGetReview(c *gin.Context, params GetUsersGetReviewParams)
	// Установить флаг активности пользователя
	// (POST /users/setIsActive)
	PostUsersSetIsActive(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// PostPullRequestCreate operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestCreate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPullRequestCreate(c)
}

// PostPullRequestMerge operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestMerge(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPullRequestMerge(c)
}

// PostPullRequestReassign operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestReassign(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPullRequestReassign(c)
}

// GetStatisticsAssignments operation middleware
func (siw *ServerInterfaceWrapper) GetStatisticsAssignments(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStatisticsAssignments(c)
}

// GetStatisticsWorkload operation middleware
func (siw *ServerInterfaceWrapper) GetStatisticsWorkload(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStatisticsWorkload(c)
}

// PostTeamAdd operation middleware
func (siw *ServerInterfaceWrapper) PostTeamAdd(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostTeamAdd(c)
}

// PostTeamDeactivate operation middleware
func (siw *ServerInterfaceWrapper) PostTeamDeactivate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostTeamDeactivate(c)
}

// GetTeamGet operation middleware
func (siw *ServerInterfaceWrapper) GetTeamGet(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamGetParams

	// ------------- Required query parameter "team_name" -------------

	if paramValue := c.Query("team_name"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument team_name is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "team_name", c.Request.URL.Query(), &params.TeamName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter team_name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTeamGet(c, params)
}

// GetUsersGetReview operation middleware
func (siw *ServerInterfaceWrapper) GetUsersGetReview(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersGetReviewParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := c.Query("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument user_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "user_id", c.Request.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersGetReview(c, params)
}

// PostUsersSetIsActive operation middleware
func (siw *ServerInterfaceWrapper) PostUsersSetIsActive(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsersSetIsActive(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.POST(options.BaseURL+"/pullRequest/create", wrapper.PostPullRequestCreate)
	router.POST(options.BaseURL+"/pullRequest/merge", wrapper.PostPullRequestMerge)
	router.POST(options.BaseURL+"/pullRequest/reassign", wrapper.PostPullRequestReassign)
	router.GET(options.BaseURL+"/statistics/assignments", wrapper.GetStatisticsAssignments)
	router.GET(options.BaseURL+"/statistics/workload", wrapper.GetStatisticsWorkload)
	router.POST(options.BaseURL+"/team/add", wrapper.PostTeamAdd)
	router.POST(options.BaseURL+"/team/deactivate", wrapper.PostTeamDeactivate)
	router.GET(options.BaseURL+"/team/get", wrapper.GetTeamGet)
	router.GET(options.BaseURL+"/users/getReview", wrapper.GetUsersGetReview)
	router.POST(options.BaseURL+"/users/setIsActive", wrapper.PostUsersSetIsActive)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xbbW8bxxH+K4ttgTgALVK01bT8xsSK6w92WEpBi7oCceKtpYvJO+bu6MQwBIhiEieV",
	"ETVFPxRBEzfIH6BoMaL1Qv2F2X9UzO7e+4tOoiwH/ZJQd3s7s7Mzz8w8u35G21a3Z5nMdB1ae0Z7mq11",
	"mcts8dcq07oPtC77U5/ZT/GBzpy2bfRcwzJpjcLPcApTOIIRHPMXcAozmBCYwgnfI3AEMziBEZzCAd+l",
	"JWrgF5+KiUrU1LqM1qjLtG5L/C5Rm33aN2ym05pr91mJOu1N1tVQqPu0h4Md1zbMDbq1VaIfO8y+p2dp",
	"9W84gAmc8h2Y8i+kfnwHZnybwBnMhKqHMIOxeDyBY76XoV7fYXbL0C+k3Jb3Uhhw2bYtu8mcnmU6DB+w",
	"z7VuryN/4jv80bZ0nOLBR6utDz/6+MEdWqJd5jjaBj61mWP17TYjpuWSR1bf1IUFerbVY7ZrMCcyVfSx",
	"nPgZZWa/S2sP6epy/X5r+S/3VlZXaIk2mpHf95ebd5dRNupRX1m5d/eB+rP1Qf3BnXt36qvL6q3Ucq0U",
	"X3xI77RdC4z4UKoWjA/mstY/YW03MV6uMDmsRBv9TqfJPu0zx01aQHMcY8NkestmTwz2mXLrqL+oXSZw",
	"CiM4xP/y5+g/cMp3+ZeEb8MExvwF/xbGMOHb6DnkRmVhofouuo3Luk7Kcn1FNdvWnuLfWt/dtIQ7pY1u",
	"20xzmV4Xa3hk2V3NpTWqay676RoiPsx+p6Oto+tIF0yxvb0x3wy9fqfTsqUtsxSNjJFxkjLKcTW374R9",
	"76PG8gNaosrLkr4T2++4KmmCwzb1RZbS9vwcv1nZtOw058ndsf8HY6XZBTE/aYsu666r6PFd/rc2e0Rr",
	"9DflIIWUFfaVcZb74pu0WAhw/1ygCKcIT4kstZXAhPKG09LarvEkLG7dsjpMM/FTD+bT9gbfFVM0SBb+",
	"N6WQ5DSdMY1dWNs8273RtYR3Im9dOJlhPrKEGMNFvKGNJmmqaCR1EZ9dZrpkhdlPjDYjN1aZ45JVzXlc",
	"Ih9qnQ6pVqpLCK9PmO1IlF5cqCxUcBVWj5laz6A1emuhsnALnV1zN4XlyptM67ib+HODuSmVwUsJ3wLG",
	"j2CE2D6CfZiJ8mCA1QEfwAz2sZThAywgCB+I0WOY8gGMqJBvazjhPZ3W6F3m/lEKRQvKPC90qVYqMgWb",
	"LjOFLlqv1zHa4tPyJw4q9CxUR0R9IAQJXsFArcc0BbMR2x1X6/YyYT+51SkbFjPUT8Giw0YawYTvEGGd",
	"bVHcqbIPFVmq3JpjwX4Fk4eOvink6PmXBqcwgQO513wIZ5j2xTROv9vVsLikcndJe5O1HxNm6j3LMF0U",
	"rW04GCpq99fwq3IvyCllmdHFSi1ZmkQ9p2E5bigHfSCHyzhkjvu+pT8tYM9QPRlKV7S/SFMyFO3ZNxcr",
	"lcXUBFGjdV0nDtPs9ibdKmXu1PVkxTkzXDoqRav4rUTELl7M4D07q8R8SPtVBM9bqMhV7ksQDrJG2MrZ",
	"KKleXpIOl86FgqfRJAIgD+EAOzvczNuV2xcK+zx9ot1SWvD+A8aylSuH+0sYiUiWFfxr1f3tSu3+cLE9",
	"jTdl4SYpaMoaTWLoROvYTNOfEva54bhObC/mWifaeQi/wITwAR/yb2AistGYDxGAYwgFP3k7wnf4C9Jo",
	"EpgSGElLoYlEI/wc54AjfBXuc6biG8RAUk1vdWAKh7Fu3p8dU0MIC0P+5KQgomhQCgPifTF6DjzMDrO8",
	"oDkXv85BpsshT+V6kCdoESlWWDcXKzert1cXq7Vbt2tLv/vrlWGTalyuH51gLABKRMuM7wl6ako8da4Z",
	"rVCfOCzFY/eliKuJCFEveo9gBEdKaXIDpuLLE1Gd7ihiC4N3j8AMSxYMQv4VTPneu8Vj0WbSewqHY9P7",
	"YI6ItDqBryqvrOb6XI7/4Fx5zc7cgVyKiHj7YY2dTn/pjRcUuIZeR2szvbWOHtpfolcXxbHJc5g47NJm",
	"8ApmyaQ0oufyITaNSlor0hi8FLNPEjTgFEN4zHcleSxaBtXyXDuaTOEYE3g6i/0iDW0uWAIprgezhFA9",
	"AKofpAw4RNw5ETC0J2sH2TUfw4T4FPITrdPPKqf8QUE51dZM03KJh0nEMonUgTSa0hSm9YFm6oauOqqo",
	"XtiShps4ydsKGMXicCpLI7RVnmoxnjvQzrSI5DqIcilBXbQ9fYhhEpdpXU9Rt67iN6boy9xN2+e7cJyg",
	"oNMqspP8RUS4+/AxgmJfDEecJHggQ1yLuJuGoyx9dSUs/AAjvs2H/OsgiA5ksvOpdTgT3MIY/ZqoVJYS",
	"f3wvmTWTQ1Uli4XqKRzha5Ens0BE2JrAAeqIQ8QwWetO5O/4AVZOZkUMNRzXaDtlzWe3nGwe6p+iYh+L",
	"zP2Nx6ocCXhRlTpW+6hEEoxeS8/+RVhTKJpxqEU87uYQ9mEKYyHgtRhOhADsF4Z8ACM4we1PobZW/HXV",
	"Q8uaN80F1qK1hx7ctHqY5xarkuCTf92KsJ10XWs/ZiZmZtdytU4rYurFpRD5KdNiwHfSesdoM7pVikp7",
	"Lyxs6SLCqhFh1aiw9611urWWkzXDBgjx6XHGPVDUr10M02UbklMPNE97m88SpywpbZLLk8kJqjt6AlCM",
	"qJMuClPJxArCNi0e0krqYz70IcHz9WAiPswIrLOccBLA62FAEBhJBPjMsh93LE2/ivDHiv+Ib/NdviMQ",
	"E4uAAxHccRAYwZFY3NjHvJzD7pxA/7On/bxRHpjhYeRMQ549Cu+VSclpta0+TpkZ7kXiupCEpQISLhrM",
	"4e3OCOVzTnTSNL14TL/dYP2vOiN4LhtTjK5XIrUeoqOeG6LeEcNzPuTfxj7HaA15t6oc0nwbJvA6L0jR",
	"gGVN1/Ob3lWmdeu6Pk+j65+Wprn+pbz5PAeNOnZPeyphvXA9t+pXsFdMkrvqOPltm8SL9TxOytO1gKGK",
	"xMT3EYY6TJxjRGBnVpmPnI7e5wmKfX/db5Cijq/usnR1pMweipp1KFBkIMp3ebvsBKbkRmBA/h3fKXvn",
	"tDAW2Vnk0ExUCDNjuIMRRNCZcKzYaV1suf+CSQiFpgKchMyxOCHOg6QEez4lsA8TMfAMV4rLSO9/VG0w",
	"xfkjtQBMSKO58DcTfoxSgBGmQpqFD8RjwncEzJ7CoVjIV4Ia9aoJNOZEHIFPgrZLdVN8oEonj3v0zsaV",
	"MwtIVroI+5xgH4U2kpZQnZYUFCdSpM6yFZwI1uIYRvxLslipwAkfeN/xgXp/qowB+/zv/Ds4kWcUUUUS",
	"FY4H63eCnZ4D3VNhJR9V/LSduKqYvCvpm+og4nIjuWPnkl+BuGvhLIPgkWSp7KT0vrR+C8uh37+HQnxa",
	"UzV6ORZLmfNZGvwkyuWDeJD6DlikbEgUXJFVJKt44ZEnmU4dIecxWsZERMax0HsAEyxtJHzyL1Plx41W",
	"zAhZPMqp6iBSRF0mnQ0VWnwt0Svb9KPrPyb+Pv9sOFmQ/kcknIHyivTYw8eFMR6R6yybUPYYl8ycpBpH",
	"9b9Ev4bj7zJXXH4KLmw/TLdbMKQcvdCNNdJ80f+rqeouXufGXOZHTCgiJnfi1N+v333j/VTRoirDAwXm",
	"ogvKO3t5jvgxDr3rj7yoP4Yv8s/vjeGzLin+jR6VrcW8teC1guKXaBNXlFOu0ma3/Zl3OqPKrBW7NHcm",
	"ctYMjkij+Y4surL4pXOcs9F8h++WCLxCb849zCp0FuI5sPDEiAM7zL3n1H3iJbvjF5+uhEbPURyGAO2R",
	"1nFYcR+59C3lzI0+75buFZeCfXWdOWmCS5FuOabyJOUFj7hcXayy+THUSX4nKyXFBqd55vXng5fFz3uj",
	"ofez5L7V4hTX9gV2WPAqRhl7LV02aZwItC3/2TPvX0zJLIKJXT2Qg0MPIqdnoechsi70VN2u3Vrb+l8A",
	"AAD//16KEFapNgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
