// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorResponseErrorCode.
const (
	NOCANDIDATE ErrorResponseErrorCode = "NO_CANDIDATE"
	NOTASSIGNED ErrorResponseErrorCode = "NOT_ASSIGNED"
	NOTFOUND    ErrorResponseErrorCode = "NOT_FOUND"
	PREXISTS    ErrorResponseErrorCode = "PR_EXISTS"
	PRMERGED    ErrorResponseErrorCode = "PR_MERGED"
	TEAMEXISTS  ErrorResponseErrorCode = "TEAM_EXISTS"
)

// Defines values for PullRequestStatus.
const (
	PullRequestStatusMERGED PullRequestStatus = "MERGED"
	PullRequestStatusOPEN   PullRequestStatus = "OPEN"
)

// Defines values for PullRequestShortStatus.
const (
	PullRequestShortStatusMERGED PullRequestShortStatus = "MERGED"
	PullRequestShortStatusOPEN   PullRequestShortStatus = "OPEN"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code    ErrorResponseErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// PullRequest defines model for PullRequest.
type PullRequest struct {
	// AssignedReviewers user_id назначенных ревьюверов (0..2)
	AssignedReviewers []string          `json:"assigned_reviewers"`
	AuthorId          string            `json:"author_id"`
	CreatedAt         *time.Time        `json:"createdAt"`
	MergedAt          *time.Time        `json:"mergedAt"`
	PullRequestId     string            `json:"pull_request_id"`
	PullRequestName   string            `json:"pull_request_name"`
	Status            PullRequestStatus `json:"status"`
}

// PullRequestStatus defines model for PullRequest.Status.
type PullRequestStatus string

// PullRequestShort defines model for PullRequestShort.
type PullRequestShort struct {
	AuthorId        string                 `json:"author_id"`
	PullRequestId   string                 `json:"pull_request_id"`
	PullRequestName string                 `json:"pull_request_name"`
	Status          PullRequestShortStatus `json:"status"`
}

// PullRequestShortStatus defines model for PullRequestShort.Status.
type PullRequestShortStatus string

// Team defines model for Team.
type Team struct {
	Members  []TeamMember `json:"members"`
	TeamName string       `json:"team_name"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	IsActive *bool  `json:"is_active,omitempty"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// User defines model for User.
type User struct {
	IsActive bool   `json:"is_active"`
	TeamName string `json:"team_name"`
	UserId   string `json:"user_id"`
	Username string `json:"username"`
}

// TeamNameQuery defines model for TeamNameQuery.
type TeamNameQuery = string

// UserIdQuery defines model for UserIdQuery.
type UserIdQuery = string

// PostPullRequestCreateJSONBody defines parameters for PostPullRequestCreate.
type PostPullRequestCreateJSONBody struct {
	AuthorId        string `json:"author_id"`
	PullRequestId   string `json:"pull_request_id"`
	PullRequestName string `json:"pull_request_name"`
}

// PostPullRequestMergeJSONBody defines parameters for PostPullRequestMerge.
type PostPullRequestMergeJSONBody struct {
	PullRequestId string `json:"pull_request_id"`
}

// PostPullRequestReassignJSONBody defines parameters for PostPullRequestReassign.
type PostPullRequestReassignJSONBody struct {
	OldUserId     string `json:"old_user_id"`
	PullRequestId string `json:"pull_request_id"`
}

// PostTeamDeactivateJSONBody defines parameters for PostTeamDeactivate.
type PostTeamDeactivateJSONBody struct {
	// TeamName Имя команды для деактивации
	TeamName string `json:"team_name"`
}

// GetTeamGetParams defines parameters for GetTeamGet.
type GetTeamGetParams struct {
	// TeamName Уникальное имя команды
	TeamName TeamNameQuery `form:"team_name" json:"team_name"`
}

// GetUsersGetReviewParams defines parameters for GetUsersGetReview.
type GetUsersGetReviewParams struct {
	// UserId Идентификатор пользователя
	UserId UserIdQuery `form:"user_id" json:"user_id"`
}

// PostUsersSetIsActiveJSONBody defines parameters for PostUsersSetIsActive.
type PostUsersSetIsActiveJSONBody struct {
	IsActive bool   `json:"is_active"`
	UserId   string `json:"user_id"`
}

// PostPullRequestCreateJSONRequestBody defines body for PostPullRequestCreate for application/json ContentType.
type PostPullRequestCreateJSONRequestBody PostPullRequestCreateJSONBody

// PostPullRequestMergeJSONRequestBody defines body for PostPullRequestMerge for application/json ContentType.
type PostPullRequestMergeJSONRequestBody PostPullRequestMergeJSONBody

// PostPullRequestReassignJSONRequestBody defines body for PostPullRequestReassign for application/json ContentType.
type PostPullRequestReassignJSONRequestBody PostPullRequestReassignJSONBody

// PostTeamAddJSONRequestBody defines body for PostTeamAdd for application/json ContentType.
type PostTeamAddJSONRequestBody = Team

// PostTeamDeactivateJSONRequestBody defines body for PostTeamDeactivate for application/json ContentType.
type PostTeamDeactivateJSONRequestBody PostTeamDeactivateJSONBody

// PostUsersSetIsActiveJSONRequestBody defines body for PostUsersSetIsActive for application/json ContentType.
type PostUsersSetIsActiveJSONRequestBody PostUsersSetIsActiveJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check endpoint
	// (GET /health)
	GetHealth(c *gin.Context)
	// Создать PR и автоматически назначить до 2 ревьюверов из команды автора
	// (POST /pullRequest/create)
	PostPullRequestCreate(c *gin.Context)
	// Пометить PR как MERGED (идемпотентная операция)
	// (POST /pullRequest/merge)
	PostPullRequestMerge(c *gin.Context)
	// Переназначить конкретного ревьювера на другого из его команды
	// (POST /pullRequest/reassign)
	PostPullRequestReassign(c *gin.Context)
	// Получить статистику назначений по пользователям
	// (GET /statistics/assignments)
	GetStatisticsAssignments(c *gin.Context)
	// Получить рабочую нагрузку активных пользователей
	// (GET /statistics/workload)
	GetStatisticsWorkload(c *gin.Context)
	// Создать команду с участниками (создаёт/обновляет пользователей)
	// (POST /team/add)
	PostTeamAdd(c *gin.Context)
	// Массовая деактивация пользователей команды с переназначением PR
	// (POST /team/deactivate)
	PostTeamDeactivate(c *gin.Context)
	// Получить команду с участниками
	// (GET /team/get)
	GetTeamGet(c *gin.Context, params GetTeamGetParams)
	// Получить PR'ы, где пользователь назначен ревьювером
	// (GET /users/getReview)
	GetUsersGetReview(c *gin.Context, params GetUsersGetReviewParams)
	// Установить флаг активности пользователя
	// (POST /users/setIsActive)
	PostUsersSetIsActive(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// PostPullRequestCreate operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestCreate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPullRequestCreate(c)
}

// PostPullRequestMerge operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestMerge(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPullRequestMerge(c)
}

// PostPullRequestReassign operation middleware
func (siw *ServerInterfaceWrapper) PostPullRequestReassign(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPullRequestReassign(c)
}

// GetStatisticsAssignments operation middleware
func (siw *ServerInterfaceWrapper) GetStatisticsAssignments(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStatisticsAssignments(c)
}

// GetStatisticsWorkload operation middleware
func (siw *ServerInterfaceWrapper) GetStatisticsWorkload(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetStatisticsWorkload(c)
}

// PostTeamAdd operation middleware
func (siw *ServerInterfaceWrapper) PostTeamAdd(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostTeamAdd(c)
}

// PostTeamDeactivate operation middleware
func (siw *ServerInterfaceWrapper) PostTeamDeactivate(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostTeamDeactivate(c)
}

// GetTeamGet operation middleware
func (siw *ServerInterfaceWrapper) GetTeamGet(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTeamGetParams

	// ------------- Required query parameter "team_name" -------------

	if paramValue := c.Query("team_name"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument team_name is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "team_name", c.Request.URL.Query(), &params.TeamName)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter team_name: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTeamGet(c, params)
}

// GetUsersGetReview operation middleware
func (siw *ServerInterfaceWrapper) GetUsersGetReview(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersGetReviewParams

	// ------------- Required query parameter "user_id" -------------

	if paramValue := c.Query("user_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument user_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "user_id", c.Request.URL.Query(), &params.UserId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter user_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetUsersGetReview(c, params)
}

// PostUsersSetIsActive operation middleware
func (siw *ServerInterfaceWrapper) PostUsersSetIsActive(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostUsersSetIsActive(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/health", wrapper.GetHealth)
	router.POST(options.BaseURL+"/pullRequest/create", wrapper.PostPullRequestCreate)
	router.POST(options.BaseURL+"/pullRequest/merge", wrapper.PostPullRequestMerge)
	router.POST(options.BaseURL+"/pullRequest/reassign", wrapper.PostPullRequestReassign)
	router.GET(options.BaseURL+"/statistics/assignments", wrapper.GetStatisticsAssignments)
	router.GET(options.BaseURL+"/statistics/workload", wrapper.GetStatisticsWorkload)
	router.POST(options.BaseURL+"/team/add", wrapper.PostTeamAdd)
	router.POST(options.BaseURL+"/team/deactivate", wrapper.PostTeamDeactivate)
	router.GET(options.BaseURL+"/team/get", wrapper.GetTeamGet)
	router.GET(options.BaseURL+"/users/getReview", wrapper.GetUsersGetReview)
	router.POST(options.BaseURL+"/users/setIsActive", wrapper.PostUsersSetIsActive)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xb724bxxF/lcW2QByAFinZalJ+Y2LFFVA7LKWgRV2BOPHW0sXkHXO3dGIYAkwpiZPK",
	"iJqiH4qgiRvkBShajGj9fYXZNypmd4/3/3gSZSXol4S629uZnZ35zcxv109py+l0HZvZ3KPVp7RruEaH",
	"cebKv1aZ0blvdNifesx9gg9M5rVcq8stx6ZVCj/BKYzhCAZwLF7AKZzBiMAYTsQegSM4gxMYwCkciF1a",
	"ohZ+8YmcqERto8NolXJmdJryd4m67JOe5TKTVrnbYyXqtTZZx0Ch/EkXB3vctewNurVVoh95zF02s7T6",
	"NxzACE7FNozF50o/sQ1n4hmBcziTqh7CGQzl4xEci70M9Xoec5uWeSHltvyX0oBLruu4DeZ1Hdtj+IB9",
	"ZnS6bfUT3+GPlmPiFPc/XG1+8OFH9+/QEu0wzzM28KnLPKfnthixHU4eOj3blBbouk6XudxiXmSq6GM1",
	"8VPK7F6HVh/Q1aXavebSX5ZXVldoidYbkd/3lhp3l1A26lFbWVm+e1//2Xy/dv/O8p3a6pJ+q7RcK8UX",
	"H9I7bdcCIz5QqgXjg7mc9Y9ZiyfGqxUmh5VovdduN9gnPebxpAUMz7M2bGY2XfbYYp9qt476i95lAqcw",
	"gEP8r3iO/gOnYld8QcQzGMFQvBDfwBBG4hl6DrlRmZtbeBvdhrOOl7LciaKG6xpP8G+jxzcd6U5po1su",
	"Mzgza3INDx23Y3BapabB2U1uyfiwe+22sY6uo1wwxfbuxmwzdHvtdtNVtsxSNDJGxUnKKI8bvOeFfe/D",
	"+tJ9WqLay5K+E9vvuCppgsM2nYgspe35FL9Z2XTcNOfJ3bH/B2Ol2QUxP2mLDuus6+iZuPxvXfaQVulv",
	"ykEKKWvsK+Ms9+Q3abEQ4P5UoAinCF+JLLW1wITyltc0Wtx6zFTwPzR6bR4LgnXHaTPDxpl81E/bKnxX",
	"TO8gd0y+SVMbM9kUhZMa5pnvDepfimxGoGMKeG9hQn3oSDEWR8ih9QZp6IAkNRmiHWZzssLcx1aLkRur",
	"zONk1fAelcgHRrtNFioLi4iwj5nrKaCen6vMVXAVTpfZRteiVXprrjJ3C/3d4JvScuVNZrT5Jv7cYDyl",
	"OHipEFwi+REMEN4HsA9nskLoY4Eg+nAG+1jNiD7WEET05eghjEUfBlTKdw2ccNmkVXqX8T8ooWhBleql",
	"LguVisrCNme21MXodttWS35a/thDhZ6GSomoD4RQwa8ZqPOIpsA2wrvHjU43E/mTW52yYTFD/RgsOmyk",
	"AYzENpHWeSbrO135oSKLlVszLHhSxOQB5MQUavTsS4NTGMGB2muxA+eY+eU0Xq/TMbC+pGp3SWuTtR4R",
	"Zptdx7I5ijY2PAwVvftr+FW5G6SVskrqcqWOqk6inlN3PB5KQ++r4SoOmcffc8wnBewZKilDGYv25mlK",
	"kqJd9+Z8pTKfmiOqtGaaxGOG29qkW6XMnbqexDhjkktHpWghv5WI2PmLGbzrZlWZD2hvAcHzFipylfsS",
	"hIMqE7ZyNkqpl5enw9VzoeCpN4gEyEM4wOYON/N25faFwj5Pn2jDlBa8/4Ch6ubK4RYTBjKSVRH/WjeA",
	"u0q7319sT+N9WbhPCvqyeoNYJjHaLjPMJ4R9Znnci+3FTOtEO+/AzzAioi92xNcwktloKHYQgGMIBT/6",
	"OyK2xQtSbxAYExgoS6GJZC/8HOeAI3wVbnXG8hvEQLKQ3u3AGA5jDf1kdkwNISwM+ZOXgoiyRykMiPfk",
	"6BnwMDvM8oJmKn5NQabLIU/lepAn6BIpVlg35ys3F26vzi9Ub92uLv7ur1eGTbp3uX50gqEEKBktZ2JP",
	"MlRj4qtzzWiF+sRhKR67L2VcjWSI+tF7BAM40kqTGzCWX57I6nRbc1sYvHsEzrBkwSAUX8JY7L1dPBZd",
	"pryncDg2/A9miEinHfiq9sqFXJ/L8R+cK6/ZmTmQSxERv3xYY6fTW3zjBQWuods2WsxsrqOH9hbp1UVx",
	"bPIcMg67tDN4BWfJpDSgUykRl0YlrRVpDF7K2UcJJnCMITwUu4o/li2DbnmuHU3GcIwJPJ3IfpGGNhcs",
	"gTTdg1lCqh4A1fdKBhwi7pxIGNpTtYPqmo9hRCYs8mOj3csqpyaDgnKqZdi2w4mPScSxidKB1BvKFLbz",
	"vmGblqk7qqhe2JKGmzhF3UoYxeJwrEojtFWeajGqO9DOdojiOoh2KUldtHx9iGUTzoyOryiv6fiNKfoy",
	"d9P2xS4cJ1jotIrsJH8REfo+fJKg2RfLk4cJPsgQ7hC+aXna0ldXwsL3MBDPxI74KgiiA5XsJuw6nEtu",
	"YYh+TXQqS4k/sZfMmsmhupLFQvUUjvC1zJNZICJtTeAAdcQhcpiqdUfqd/wMKyezIoZaHrdaXtmYsFte",
	"Ng/1T1mxD2Xm/tpnVY4kvOhKHat9VCIJRq+VZ/8srSkVzTjXIj53cwj7MIahFPBaDidSAPYLO6IPAzjB",
	"7U+htlYm66qFljVrmgusRasPfLhpdjHPzS8ogk/9dSvCdtJ1o/WI2ZiZucONdjNi6vnFEPmp0mLAd9Ja",
	"22oxulWKSnsnLGzxIsIWIsIWosLec9bp1lpO1gwbIESpx0n3QNFJ7WLZnG0oWj3QPO1tPkucsqS0SS5P",
	"Jieo7ughQDGiTrkojBUTKwnbtHhIK6mPxc4EEnxfDyYSOxmBdZ4TThJ4fQwIAiOJAJ867qO2Y5hXEf5Y",
	"8R+JZ2JXbEvExCLgQAZ3HAQGcCQXN5xgXs55d06g/9nXftYoD8zwIHKmoU5epPeqpOQ1W04Pp8wM9yJx",
	"XUjCYgEJFw3m8HZnhPKUE500TS8e079ssP5XnxE8V40pRtcrmVoP0VGnhqh/xPBc7IhvYp9jtIa8W1cO",
	"ab4NI3idF6RowLJhmvlN7yozOjXTnKXRnRyYprn+pbx5moNGHbtrPFGwXrieW51UsFdMknN9ovxLm8SP",
	"9TxOyte1gKGKxMR3EYY6TJxjRGBnVpmNnI5e6QmK/cm63yBFHV/dZenqSJm9I2vWHYkifVm+qwtmJzAm",
	"NwIDim/Fdtk/p4WhzM4yh2aiQpgZwx2MIILJpGPFTutiy/0XjEIoNJbgJGUO5QlxHiQl2PMxgX0YyYHn",
	"uFJcRnr/o2uDMc4fqQVgROqNub/Z8EOUAowwFcosoi8fE7EtYfYUDuVCvpTUqF9NoDFH8gh8FLRdupsS",
	"fV06+dyjfzaunVlCstZF2ucE+yi0kbKE7rSUoDiRonRWreBIshbHMBBfkPlKBU5E3/9O9PX7U20M2Bd/",
	"F9/CiTqjiCqSqHB8WL8T7PQM6J4KK/moMknbiduKyeuSE1MdRFxuoHZsKvkViLsWzjIIHkWWqk7K7Cnr",
	"N7EcevcdFDKhNXWjl2OxlDmfpsFPolw+iAfpxAGLlA2JgiuyimQVLz3yJNOpI+Q8RsuQyMg4lnr3YYSl",
	"jYJP8UWq/LjRihkhi0c51R1EiqjLpLMdjRZfKfTKNv3g+o+Jv8s/G04WpP+RCaevvSI99vBxYYxH5DrP",
	"JpR9xiUzJ+nGUf8v0a/h+LuMy8tPwZ3tB+l2C4aUo3e6sUaaLfp/NVXdxevcmMv8gAlFxuR2nPr79btv",
	"vJ8qWlRleKDEXHRBdWcvzxE/wqF3JyMv6o/hu/yze2P4rEuJf6NHZWsxby14raD4PdrELeWU27TZbX/m",
	"nc6oMmvFLs2dy5x1Bkek3nhLFV1Z/NIU56w33hK7JQKv0JtzD7MKnYX4Diw9MeLAHuPLXm1CvGR3/PLT",
	"ldDoGYrDEKA9NNoeK+4jU1iiS2z0tFu6V1wK9vR15qQJLkW65ZjKl5QXPPJydbHK5odQJ/mtqpQ0G5zm",
	"mdefD14WP++Nht5PivvWi9Nc2+fYYcGrGGXst3TZpHEi0FAWcx/7UB9V+o9Oy2iTWn2ZqDG4wW6bVukm",
	"512vWi63ccCm4/Hqu5V3KyqzKwlP/X+CpXISlgn6gRIdehA5iws9D1F/oaf6ru7W2tb/AgAA//8CJ2h+",
	"+jYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
