// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PrReviewer struct {
	ID            int64            `json:"id"`
	PullRequestID string           `json:"pull_request_id"`
	UserID        string           `json:"user_id"`
	AssignedAt    pgtype.Timestamp `json:"assigned_at"`
}

type PullRequest struct {
	ID              int64            `json:"id"`
	PullRequestID   string           `json:"pull_request_id"`
	PullRequestName string           `json:"pull_request_name"`
	AuthorID        string           `json:"author_id"`
	Status          string           `json:"status"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	MergedAt        pgtype.Timestamp `json:"merged_at"`
}

type Team struct {
	ID        int64            `json:"id"`
	TeamName  string           `json:"team_name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        int64            `json:"id"`
	UserID    string           `json:"user_id"`
	Username  string           `json:"username"`
	TeamID    int64            `json:"team_id"`
	IsActive  bool             `json:"is_active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
