// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pr_reviewers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReviewer = `-- name: AddReviewer :one
INSERT INTO pr_reviewers (pull_request_id, user_id)
VALUES ($1, $2)
RETURNING id, pull_request_id, user_id, assigned_at
`

type AddReviewerParams struct {
	PullRequestID string `json:"pull_request_id"`
	UserID        string `json:"user_id"`
}

func (q *Queries) AddReviewer(ctx context.Context, arg AddReviewerParams) (PrReviewer, error) {
	row := q.db.QueryRow(ctx, addReviewer, arg.PullRequestID, arg.UserID)
	var i PrReviewer
	err := row.Scan(
		&i.ID,
		&i.PullRequestID,
		&i.UserID,
		&i.AssignedAt,
	)
	return i, err
}

const countReviewersByPRID = `-- name: CountReviewersByPRID :one
SELECT COUNT(*) FROM pr_reviewers
WHERE pull_request_id = $1
`

func (q *Queries) CountReviewersByPRID(ctx context.Context, pullRequestID string) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewersByPRID, pullRequestID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOpenPRsWithInactiveReviewers = `-- name: GetOpenPRsWithInactiveReviewers :many
SELECT DISTINCT p.pull_request_id, p.author_id, pr.user_id as inactive_reviewer_id, u.team_id
FROM pull_requests p
JOIN pr_reviewers pr ON p.pull_request_id = pr.pull_request_id
JOIN users u ON pr.user_id = u.user_id
WHERE p.status = 'OPEN' AND u.is_active = false
ORDER BY p.pull_request_id
`

type GetOpenPRsWithInactiveReviewersRow struct {
	PullRequestID      string `json:"pull_request_id"`
	AuthorID           string `json:"author_id"`
	InactiveReviewerID string `json:"inactive_reviewer_id"`
	TeamID             int64  `json:"team_id"`
}

func (q *Queries) GetOpenPRsWithInactiveReviewers(ctx context.Context) ([]GetOpenPRsWithInactiveReviewersRow, error) {
	rows, err := q.db.Query(ctx, getOpenPRsWithInactiveReviewers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOpenPRsWithInactiveReviewersRow{}
	for rows.Next() {
		var i GetOpenPRsWithInactiveReviewersRow
		if err := rows.Scan(
			&i.PullRequestID,
			&i.AuthorID,
			&i.InactiveReviewerID,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPullRequestsByReviewerUserID = `-- name: GetPullRequestsByReviewerUserID :many
SELECT pr.id, pr.pull_request_id, pr.user_id, pr.assigned_at, p.pull_request_name, p.author_id, p.status, p.created_at, p.merged_at
FROM pr_reviewers pr
JOIN pull_requests p ON pr.pull_request_id = p.pull_request_id
WHERE pr.user_id = $1
ORDER BY p.created_at DESC
`

type GetPullRequestsByReviewerUserIDRow struct {
	ID              int64            `json:"id"`
	PullRequestID   string           `json:"pull_request_id"`
	UserID          string           `json:"user_id"`
	AssignedAt      pgtype.Timestamp `json:"assigned_at"`
	PullRequestName string           `json:"pull_request_name"`
	AuthorID        string           `json:"author_id"`
	Status          string           `json:"status"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	MergedAt        pgtype.Timestamp `json:"merged_at"`
}

func (q *Queries) GetPullRequestsByReviewerUserID(ctx context.Context, userID string) ([]GetPullRequestsByReviewerUserIDRow, error) {
	rows, err := q.db.Query(ctx, getPullRequestsByReviewerUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPullRequestsByReviewerUserIDRow{}
	for rows.Next() {
		var i GetPullRequestsByReviewerUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PullRequestID,
			&i.UserID,
			&i.AssignedAt,
			&i.PullRequestName,
			&i.AuthorID,
			&i.Status,
			&i.CreatedAt,
			&i.MergedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewersByPRID = `-- name: GetReviewersByPRID :many
SELECT pr.id, pr.pull_request_id, pr.user_id, pr.assigned_at, u.username, u.team_id, u.is_active
FROM pr_reviewers pr
JOIN users u ON pr.user_id = u.user_id
WHERE pr.pull_request_id = $1
ORDER BY pr.assigned_at
`

type GetReviewersByPRIDRow struct {
	ID            int64            `json:"id"`
	PullRequestID string           `json:"pull_request_id"`
	UserID        string           `json:"user_id"`
	AssignedAt    pgtype.Timestamp `json:"assigned_at"`
	Username      string           `json:"username"`
	TeamID        int64            `json:"team_id"`
	IsActive      bool             `json:"is_active"`
}

func (q *Queries) GetReviewersByPRID(ctx context.Context, pullRequestID string) ([]GetReviewersByPRIDRow, error) {
	rows, err := q.db.Query(ctx, getReviewersByPRID, pullRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReviewersByPRIDRow{}
	for rows.Next() {
		var i GetReviewersByPRIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PullRequestID,
			&i.UserID,
			&i.AssignedAt,
			&i.Username,
			&i.TeamID,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserAssignedToPR = `-- name: IsUserAssignedToPR :one
SELECT EXISTS(
    SELECT 1 FROM pr_reviewers
    WHERE pull_request_id = $1 AND user_id = $2
)
`

type IsUserAssignedToPRParams struct {
	PullRequestID string `json:"pull_request_id"`
	UserID        string `json:"user_id"`
}

func (q *Queries) IsUserAssignedToPR(ctx context.Context, arg IsUserAssignedToPRParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserAssignedToPR, arg.PullRequestID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeInactiveReviewers = `-- name: RemoveInactiveReviewers :exec
DELETE FROM pr_reviewers
WHERE pull_request_id = $1 AND user_id = ANY($2::text[])
`

type RemoveInactiveReviewersParams struct {
	PullRequestID string   `json:"pull_request_id"`
	Column2       []string `json:"column_2"`
}

func (q *Queries) RemoveInactiveReviewers(ctx context.Context, arg RemoveInactiveReviewersParams) error {
	_, err := q.db.Exec(ctx, removeInactiveReviewers, arg.PullRequestID, arg.Column2)
	return err
}

const removeReviewer = `-- name: RemoveReviewer :exec
DELETE FROM pr_reviewers
WHERE pull_request_id = $1 AND user_id = $2
`

type RemoveReviewerParams struct {
	PullRequestID string `json:"pull_request_id"`
	UserID        string `json:"user_id"`
}

func (q *Queries) RemoveReviewer(ctx context.Context, arg RemoveReviewerParams) error {
	_, err := q.db.Exec(ctx, removeReviewer, arg.PullRequestID, arg.UserID)
	return err
}

const replaceReviewer = `-- name: ReplaceReviewer :exec
UPDATE pr_reviewers
SET user_id = $3, assigned_at = NOW()
WHERE pull_request_id = $1 AND user_id = $2
`

type ReplaceReviewerParams struct {
	PullRequestID string `json:"pull_request_id"`
	UserID        string `json:"user_id"`
	UserID_2      string `json:"user_id_2"`
}

func (q *Queries) ReplaceReviewer(ctx context.Context, arg ReplaceReviewerParams) error {
	_, err := q.db.Exec(ctx, replaceReviewer, arg.PullRequestID, arg.UserID, arg.UserID_2)
	return err
}
