// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddReviewer(ctx context.Context, arg AddReviewerParams) (PrReviewer, error)
	CountReviewersByPRID(ctx context.Context, pullRequestID string) (int64, error)
	CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) (PullRequest, error)
	CreateTeam(ctx context.Context, teamName string) (Team, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateTeamUsers(ctx context.Context, teamID int64) ([]User, error)
	// Статистика назначений по пользователям
	GetAssignmentStats(ctx context.Context) ([]GetAssignmentStatsRow, error)
	GetOpenPRsWithInactiveReviewers(ctx context.Context) ([]GetOpenPRsWithInactiveReviewersRow, error)
	// Статистика по Pull Request'ам
	GetPRStats(ctx context.Context) ([]GetPRStatsRow, error)
	GetPullRequestByID(ctx context.Context, id int64) (PullRequest, error)
	GetPullRequestByPRID(ctx context.Context, pullRequestID string) (PullRequest, error)
	GetPullRequestsByReviewerUserID(ctx context.Context, userID string) ([]GetPullRequestsByReviewerUserIDRow, error)
	GetReviewersByPRID(ctx context.Context, pullRequestID string) ([]GetReviewersByPRIDRow, error)
	GetTeamByID(ctx context.Context, id int64) (Team, error)
	GetTeamByName(ctx context.Context, teamName string) (Team, error)
	// Статистика по командам
	GetTeamStats(ctx context.Context) ([]GetTeamStatsRow, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUserID(ctx context.Context, userID string) (User, error)
	GetUserWithTeam(ctx context.Context, userID string) (GetUserWithTeamRow, error)
	// Рабочая нагрузка пользователей (только открытые PR)
	GetUserWorkload(ctx context.Context) ([]GetUserWorkloadRow, error)
	IsUserAssignedToPR(ctx context.Context, arg IsUserAssignedToPRParams) (bool, error)
	ListActiveUsersByTeamID(ctx context.Context, teamID int64) ([]User, error)
	ListActiveUsersByTeamIDExcludingUser(ctx context.Context, arg ListActiveUsersByTeamIDExcludingUserParams) ([]User, error)
	ListPullRequests(ctx context.Context) ([]PullRequest, error)
	ListPullRequestsByStatus(ctx context.Context, status string) ([]PullRequest, error)
	ListTeams(ctx context.Context) ([]Team, error)
	ListUsersByTeamID(ctx context.Context, teamID int64) ([]User, error)
	MergePullRequest(ctx context.Context, pullRequestID string) (PullRequest, error)
	PullRequestExists(ctx context.Context, pullRequestID string) (bool, error)
	RemoveInactiveReviewers(ctx context.Context, arg RemoveInactiveReviewersParams) error
	RemoveReviewer(ctx context.Context, arg RemoveReviewerParams) error
	ReplaceReviewer(ctx context.Context, arg ReplaceReviewerParams) error
	TeamExists(ctx context.Context, teamName string) (bool, error)
	UpdatePullRequestStatus(ctx context.Context, arg UpdatePullRequestStatusParams) (PullRequest, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserIsActive(ctx context.Context, arg UpdateUserIsActiveParams) (User, error)
	UserExists(ctx context.Context, userID string) (bool, error)
}

var _ Querier = (*Queries)(nil)
