// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package db

import (
	"context"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (team_name)
VALUES ($1)
RETURNING id, team_name, created_at
`

func (q *Queries) CreateTeam(ctx context.Context, teamName string) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, teamName)
	var i Team
	err := row.Scan(&i.ID, &i.TeamName, &i.CreatedAt)
	return i, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, team_name, created_at FROM teams
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTeamByID(ctx context.Context, id int64) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(&i.ID, &i.TeamName, &i.CreatedAt)
	return i, err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT id, team_name, created_at FROM teams
WHERE team_name = $1 LIMIT 1
`

func (q *Queries) GetTeamByName(ctx context.Context, teamName string) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByName, teamName)
	var i Team
	err := row.Scan(&i.ID, &i.TeamName, &i.CreatedAt)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT id, team_name, created_at FROM teams
ORDER BY team_name
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(&i.ID, &i.TeamName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const teamExists = `-- name: TeamExists :one
SELECT EXISTS(SELECT 1 FROM teams WHERE team_name = $1)
`

func (q *Queries) TeamExists(ctx context.Context, teamName string) (bool, error) {
	row := q.db.QueryRow(ctx, teamExists, teamName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
