// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_id, username, team_id, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, username, team_id, is_active, created_at, updated_at
`

type CreateUserParams struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
	TeamID   int64  `json:"team_id"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.Username,
		arg.TeamID,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.TeamID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateTeamUsers = `-- name: DeactivateTeamUsers :many
UPDATE users
SET is_active = false, updated_at = NOW()
WHERE team_id = $1 AND is_active = true
RETURNING id, user_id, username, team_id, is_active, created_at, updated_at
`

func (q *Queries) DeactivateTeamUsers(ctx context.Context, teamID int64) ([]User, error) {
	rows, err := q.db.Query(ctx, deactivateTeamUsers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.TeamID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, user_id, username, team_id, is_active, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.TeamID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUserID = `-- name: GetUserByUserID :one
SELECT id, user_id, username, team_id, is_active, created_at, updated_at FROM users
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByUserID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUserID, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.TeamID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserWithTeam = `-- name: GetUserWithTeam :one
SELECT u.id, u.user_id, u.username, u.team_id, u.is_active, u.created_at, u.updated_at, t.team_name
FROM users u
JOIN teams t ON u.team_id = t.id
WHERE u.user_id = $1 LIMIT 1
`

type GetUserWithTeamRow struct {
	ID        int64            `json:"id"`
	UserID    string           `json:"user_id"`
	Username  string           `json:"username"`
	TeamID    int64            `json:"team_id"`
	IsActive  bool             `json:"is_active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	TeamName  string           `json:"team_name"`
}

func (q *Queries) GetUserWithTeam(ctx context.Context, userID string) (GetUserWithTeamRow, error) {
	row := q.db.QueryRow(ctx, getUserWithTeam, userID)
	var i GetUserWithTeamRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.TeamID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TeamName,
	)
	return i, err
}

const listActiveUsersByTeamID = `-- name: ListActiveUsersByTeamID :many
SELECT id, user_id, username, team_id, is_active, created_at, updated_at FROM users
WHERE team_id = $1 AND is_active = true
ORDER BY username
`

func (q *Queries) ListActiveUsersByTeamID(ctx context.Context, teamID int64) ([]User, error) {
	rows, err := q.db.Query(ctx, listActiveUsersByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.TeamID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveUsersByTeamIDExcludingUser = `-- name: ListActiveUsersByTeamIDExcludingUser :many
SELECT id, user_id, username, team_id, is_active, created_at, updated_at FROM users
WHERE team_id = $1 AND is_active = true AND user_id != $2
ORDER BY username
`

type ListActiveUsersByTeamIDExcludingUserParams struct {
	TeamID int64  `json:"team_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) ListActiveUsersByTeamIDExcludingUser(ctx context.Context, arg ListActiveUsersByTeamIDExcludingUserParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listActiveUsersByTeamIDExcludingUser, arg.TeamID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.TeamID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTeamID = `-- name: ListUsersByTeamID :many
SELECT id, user_id, username, team_id, is_active, created_at, updated_at FROM users
WHERE team_id = $1
ORDER BY username
`

func (q *Queries) ListUsersByTeamID(ctx context.Context, teamID int64) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.TeamID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $2, team_id = $3, is_active = $4, updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, username, team_id, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	UserID   string `json:"user_id"`
	Username string `json:"username"`
	TeamID   int64  `json:"team_id"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserID,
		arg.Username,
		arg.TeamID,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.TeamID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserIsActive = `-- name: UpdateUserIsActive :one
UPDATE users
SET is_active = $2, updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, username, team_id, is_active, created_at, updated_at
`

type UpdateUserIsActiveParams struct {
	UserID   string `json:"user_id"`
	IsActive bool   `json:"is_active"`
}

func (q *Queries) UpdateUserIsActive(ctx context.Context, arg UpdateUserIsActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserIsActive, arg.UserID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.TeamID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1 FROM users WHERE user_id = $1)
`

func (q *Queries) UserExists(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, userExists, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
